"""
Code Exporter — Exports the cleaning pipeline as reproducible code/specs.
Supports: Python script, Jupyter Notebook, JSON pipeline, SQL script.
"""

from __future__ import annotations

import json
from typing import Optional


class CodeExporter:
    """Export preprocessing pipelines and queries as reusable code."""

    @staticmethod
    def to_python_script(audit_log: list[dict], file_name: str = "dataset.csv") -> str:
        """Generate a production-ready Python script from the audit log."""
        lines = [
            '"""',
            f"Auto-generated preprocessing pipeline for {file_name}",
            "Generated by Data Intelligence Platform",
            '"""',
            "",
            "import pandas as pd",
            "import numpy as np",
            "from sklearn.preprocessing import StandardScaler, LabelEncoder",
            "",
            "",
            f'# ── Step 0: Load data ────────────────────────────────────────────',
            f'df = pd.read_csv("{file_name}")',
            f'print(f"Loaded: {{df.shape[0]:,}} rows × {{df.shape[1]}} columns")',
            "",
        ]

        for i, entry in enumerate(audit_log, 1):
            step_name = entry.get("step_name", f"Step {i}")
            action = entry.get("action_type", "unknown")
            status = entry.get("status", "applied")
            reason = entry.get("trigger_reason", "")
            cols = entry.get("columns_affected", [])
            code = entry.get("pipeline_code", "")

            lines.append(f"# ── Step {i}: {step_name} ──")
            lines.append(f"# Action: {action}")
            lines.append(f"# Status: {status}")
            if reason:
                lines.append(f"# Reason: {reason}")
            if cols:
                lines.append(f"# Columns: {', '.join(cols[:5])}")

            if status == "skipped":
                lines.append(f"# SKIPPED — {reason}")
            elif code:
                lines.append(code)
            else:
                # Generate default code from action type
                lines.append(CodeExporter._default_code(action, cols))

            lines.append("")

        lines.extend([
            '# ── Final: Save cleaned data ──────────────────────────────────',
            'output_file = "cleaned_" + "' + file_name + '"',
            "df.to_csv(output_file, index=False)",
            'print(f"Saved: {df.shape[0]:,} rows × {df.shape[1]} columns → {output_file}")',
        ])

        return "\n".join(lines)

    @staticmethod
    def to_notebook(audit_log: list[dict], file_name: str = "dataset.csv") -> str:
        """Generate a Jupyter Notebook with step-by-step code."""
        cells = []

        # Title
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🧹 Data Preprocessing Pipeline\n",
                f"*Auto-generated for `{file_name}`*\n",
            ],
        })

        # Load data
        cells.append({
            "cell_type": "code",
            "metadata": {},
            "execution_count": None,
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "import numpy as np\n",
                "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
                "\n",
                f'df = pd.read_csv("{file_name}")\n',
                "print(f\"Shape: {df.shape}\")\n",
                "df.head()\n",
            ],
        })

        for i, entry in enumerate(audit_log, 1):
            step_name = entry.get("step_name", f"Step {i}")
            action = entry.get("action_type", "unknown")
            status = entry.get("status", "applied")
            reason = entry.get("trigger_reason", "")
            code = entry.get("pipeline_code", "")
            cols = entry.get("columns_affected", [])

            # Markdown explain
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"## Step {i}: {step_name}\n",
                    f"**Action:** {action}  \n",
                    f"**Status:** {status}  \n",
                    f"**Reason:** {reason}\n",
                ],
            })

            # Code cell
            if status != "skipped":
                src = code if code else CodeExporter._default_code(action, cols)
                cells.append({
                    "cell_type": "code",
                    "metadata": {},
                    "execution_count": None,
                    "outputs": [],
                    "source": [src + "\n", "df.shape\n"],
                })

        # Save
        cells.append({
            "cell_type": "code",
            "metadata": {},
            "execution_count": None,
            "outputs": [],
            "source": [
                f'df.to_csv("cleaned_{file_name}", index=False)\n',
                f'print("Done! Saved cleaned_{file_name}")\n',
            ],
        })

        notebook = {
            "nbformat": 4,
            "nbformat_minor": 5,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3",
                },
            },
            "cells": cells,
        }
        return json.dumps(notebook, indent=2)

    @staticmethod
    def to_json_pipeline(audit_log: list[dict]) -> str:
        """Export pipeline as JSON specification (machine-readable)."""
        pipeline = {
            "version": "1.0",
            "platform": "Data Intelligence Platform",
            "steps": [],
        }

        for entry in audit_log:
            pipeline["steps"].append({
                "step_name": entry.get("step_name", ""),
                "action_type": entry.get("action_type", ""),
                "status": entry.get("status", "applied"),
                "trigger_reason": entry.get("trigger_reason", ""),
                "columns_affected": entry.get("columns_affected", []),
                "rows_before": entry.get("rows_before", 0),
                "rows_after": entry.get("rows_after", 0),
                "pipeline_code": entry.get("pipeline_code", ""),
            })

        return json.dumps(pipeline, indent=2)

    @staticmethod
    def to_sql_file(queries: list[dict]) -> str:
        """Export saved SQL queries as a .sql file."""
        lines = [
            "-- ==================================================",
            "-- Exported SQL Queries",
            "-- Data Intelligence Platform",
            "-- ==================================================",
            "",
        ]

        for i, q in enumerate(queries, 1):
            name = q.get("name", f"Query {i}")
            desc = q.get("description", "")
            sql = q.get("sql", "")

            lines.append(f"-- [{i}] {name}")
            if desc:
                lines.append(f"-- {desc}")
            lines.append(sql + ";")
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def _default_code(action_type: str, columns: list[str]) -> str:
        """Generate default Python code for common action types."""
        col_str = ", ".join(f'"{c}"' for c in columns[:5])

        code_map = {
            "drop_nulls": f"df = df.dropna(subset=[{col_str}])",
            "fill_nulls": f"for col in [{col_str}]:\n    df[col] = df[col].fillna(df[col].median())",
            "fill_nulls_mean": f"for col in [{col_str}]:\n    df[col] = df[col].fillna(df[col].mean())",
            "fill_nulls_median": f"for col in [{col_str}]:\n    df[col] = df[col].fillna(df[col].median())",
            "fill_nulls_mode": f"for col in [{col_str}]:\n    df[col] = df[col].fillna(df[col].mode()[0])",
            "drop_duplicates": "df = df.drop_duplicates()",
            "remove_outliers": f"for col in [{col_str}]:\n    q1, q3 = df[col].quantile([0.25, 0.75])\n    iqr = q3 - q1\n    df = df[(df[col] >= q1 - 1.5*iqr) & (df[col] <= q3 + 1.5*iqr)]",
            "standardize": f"from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\ndf[[{col_str}]] = scaler.fit_transform(df[[{col_str}]])",
            "label_encode": f"from sklearn.preprocessing import LabelEncoder\nle = LabelEncoder()\nfor col in [{col_str}]:\n    df[col] = le.fit_transform(df[col].astype(str))",
            "one_hot_encode": f"df = pd.get_dummies(df, columns=[{col_str}], drop_first=True)",
            "drop_columns": f"df = df.drop(columns=[{col_str}])",
            "convert_type": f"# Type conversion applied to: {col_str}",
        }

        return code_map.get(action_type, f"# {action_type} applied to: {col_str}")
