/**
 * StoryBuilder — Create data presentations with auto-generated narrative slides.
 */

import React, { useState, useCallback } from 'react';
import { Button, Space, Tag, Input, Select, Modal, Empty, Tooltip } from 'antd';
import {
    ReadOutlined, DeleteOutlined, ArrowUpOutlined,
    ArrowDownOutlined, PlayCircleOutlined, DownloadOutlined,
    EditOutlined,
} from '@ant-design/icons';

const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:8000';

interface Slide {
    id: string;
    type: 'title' | 'insight' | 'chart' | 'text' | 'kpi' | 'comparison';
    title: string;
    content: string;
    chartConfig?: any;
    kpiValue?: string | number;
    kpiLabel?: string;
}

interface Props {
    fileId: string;
    insights?: any[];
}

const SLIDE_TYPES = [
    { value: 'title', label: '📌 Title Slide', icon: '📌' },
    { value: 'insight', label: '💡 Insight', icon: '💡' },
    { value: 'chart', label: '📊 Chart', icon: '📊' },
    { value: 'text', label: '📝 Text', icon: '📝' },
    { value: 'kpi', label: '🎯 KPI Card', icon: '🎯' },
    { value: 'comparison', label: '⚖️ Comparison', icon: '⚖️' },
];

const StoryBuilder: React.FC<Props> = ({ fileId }) => {
    const [slides, setSlides] = useState<Slide[]>([{
        id: '0',
        type: 'title',
        title: 'Data Analysis Report',
        content: 'Generated by Data Intelligence Platform',
    }]);
    const [presenting, setPresenting] = useState(false);
    const [currentSlide, setCurrentSlide] = useState(0);
    const [editModal, setEditModal] = useState<{ visible: boolean; slide?: Slide }>({ visible: false });
    const [generating, setGenerating] = useState(false);

    const addSlide = useCallback((type: string) => {
        setSlides(prev => [...prev, {
            id: Date.now().toString(),
            type: type as any,
            title: `Slide ${prev.length + 1}`,
            content: '',
        }]);
    }, []);

    const updateSlide = useCallback((id: string, updates: Partial<Slide>) => {
        setSlides(prev => prev.map(s => s.id === id ? { ...s, ...updates } : s));
    }, []);

    const removeSlide = useCallback((id: string) => {
        setSlides(prev => prev.filter(s => s.id !== id));
    }, []);

    const moveSlide = useCallback((id: string, direction: 'up' | 'down') => {
        setSlides(prev => {
            const idx = prev.findIndex(s => s.id === id);
            if (idx < 0) return prev;
            const newIdx = direction === 'up' ? idx - 1 : idx + 1;
            if (newIdx < 0 || newIdx >= prev.length) return prev;
            const re = [...prev];
            [re[idx], re[newIdx]] = [re[newIdx], re[idx]];
            return re;
        });
    }, []);

    const autoGenerate = useCallback(async () => {
        setGenerating(true);
        try {
            const res = await fetch(`${API_BASE}/api/story/generate`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ file_id: fileId }),
            });
            const data = await res.json();
            if (data.slides) setSlides(data.slides);
        } catch (e: any) {
            console.error('Auto-generate error:', e);
        } finally {
            setGenerating(false);
        }
    }, [fileId]);

    const exportStory = useCallback(async (format: 'html' | 'pdf') => {
        try {
            const res = await fetch(`${API_BASE}/api/story/export`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ slides, format }),
            });
            const blob = await res.blob();
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `data_story.${format}`;
            a.click();
        } catch (e: any) {
            console.error('Export error:', e);
        }
    }, [slides]);

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {/* Toolbar */}
            <div className="glass-panel" style={{
                padding: '8px 12px', display: 'flex', justifyContent: 'space-between',
                alignItems: 'center', flexWrap: 'wrap', gap: 8,
            }}>
                <Space>
                    <ReadOutlined style={{ color: '#6366f1', fontSize: 18 }} />
                    <strong>Data Story Builder</strong>
                    <Tag color="purple">{slides.length} slides</Tag>
                </Space>
                <Space>
                    <Button size="small" icon={<PlayCircleOutlined />}
                        onClick={autoGenerate} loading={generating}>
                        Auto-Generate
                    </Button>
                    <Select size="small" placeholder="Add slide" style={{ width: 140 }}
                        onSelect={v => addSlide(v)}>
                        {SLIDE_TYPES.map(t => (
                            <Select.Option key={t.value} value={t.value}>
                                {t.label}
                            </Select.Option>
                        ))}
                    </Select>
                    <Button size="small" icon={<PlayCircleOutlined />}
                        type="primary" onClick={() => { setPresenting(true); setCurrentSlide(0); }}>
                        Present
                    </Button>
                    <Button size="small" icon={<DownloadOutlined />}
                        onClick={() => exportStory('html')}>
                        Export
                    </Button>
                </Space>
            </div>

            {/* Slide list */}
            {slides.map((slide, i) => (
                <div key={slide.id} className="glass-panel" style={{
                    padding: '10px 14px', display: 'flex', alignItems: 'center', gap: 10,
                    borderLeft: `3px solid ${slide.type === 'title' ? '#6366f1' : slide.type === 'insight' ? '#fbbf24' : '#3b82f6'}`,
                }}>
                    <Tag style={{ fontSize: 14, margin: 0 }}>
                        {SLIDE_TYPES.find(t => t.value === slide.type)?.icon || '📄'}
                    </Tag>
                    <div style={{ flex: 1 }}>
                        <div style={{ fontWeight: 600, fontSize: 13 }}>{slide.title}</div>
                        <div style={{ fontSize: 11, opacity: 0.5, maxHeight: 20, overflow: 'hidden' }}>
                            {slide.content || 'No content yet'}
                        </div>
                    </div>
                    <Space size={2}>
                        <Tooltip title="Move up">
                            <Button size="small" icon={<ArrowUpOutlined />}
                                disabled={i === 0} onClick={() => moveSlide(slide.id, 'up')} />
                        </Tooltip>
                        <Tooltip title="Move down">
                            <Button size="small" icon={<ArrowDownOutlined />}
                                disabled={i === slides.length - 1} onClick={() => moveSlide(slide.id, 'down')} />
                        </Tooltip>
                        <Tooltip title="Edit">
                            <Button size="small" icon={<EditOutlined />}
                                onClick={() => setEditModal({ visible: true, slide })} />
                        </Tooltip>
                        <Tooltip title="Delete">
                            <Button size="small" icon={<DeleteOutlined />} danger
                                onClick={() => removeSlide(slide.id)} />
                        </Tooltip>
                    </Space>
                </div>
            ))}

            {slides.length === 0 && (
                <Empty description="Add slides to start building your data story" />
            )}

            {/* Edit Modal */}
            <Modal
                title={`Edit Slide — ${editModal.slide?.type}`}
                open={editModal.visible}
                onCancel={() => setEditModal({ visible: false })}
                onOk={() => {
                    if (editModal.slide) updateSlide(editModal.slide.id, editModal.slide);
                    setEditModal({ visible: false });
                }}
                width={600}
            >
                {editModal.slide && (
                    <Space direction="vertical" style={{ width: '100%' }}>
                        <Input
                            value={editModal.slide.title}
                            onChange={e => setEditModal(prev => ({
                                ...prev,
                                slide: prev.slide ? { ...prev.slide, title: e.target.value } : undefined,
                            }))}
                            placeholder="Slide title"
                        />
                        <Input.TextArea
                            value={editModal.slide.content}
                            onChange={e => setEditModal(prev => ({
                                ...prev,
                                slide: prev.slide ? { ...prev.slide, content: e.target.value } : undefined,
                            }))}
                            rows={6}
                            placeholder="Slide content"
                        />
                        {editModal.slide.type === 'kpi' && (
                            <Space>
                                <Input
                                    value={editModal.slide.kpiLabel || ''}
                                    onChange={e => setEditModal(prev => ({
                                        ...prev,
                                        slide: prev.slide ? { ...prev.slide, kpiLabel: e.target.value } : undefined,
                                    }))}
                                    placeholder="KPI Label"
                                    style={{ width: 200 }}
                                />
                                <Input
                                    value={String(editModal.slide.kpiValue || '')}
                                    onChange={e => setEditModal(prev => ({
                                        ...prev,
                                        slide: prev.slide ? { ...prev.slide, kpiValue: e.target.value } : undefined,
                                    }))}
                                    placeholder="KPI Value"
                                    style={{ width: 150 }}
                                />
                            </Space>
                        )}
                    </Space>
                )}
            </Modal>

            {/* Presentation Modal (simplified) */}
            <Modal
                open={presenting}
                onCancel={() => setPresenting(false)}
                width="90vw"
                footer={
                    <Space>
                        <Button disabled={currentSlide === 0}
                            onClick={() => setCurrentSlide(p => p - 1)}>
                            ← Previous
                        </Button>
                        <span>{currentSlide + 1} / {slides.length}</span>
                        <Button disabled={currentSlide >= slides.length - 1}
                            onClick={() => setCurrentSlide(p => p + 1)}>
                            Next →
                        </Button>
                    </Space>
                }
                styles={{
                    body: {
                        minHeight: '60vh', display: 'flex', flexDirection: 'column',
                        justifyContent: 'center', alignItems: 'center', padding: 40,
                    }
                }}
            >
                {slides[currentSlide] && (
                    <>
                        <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 16 }}>
                            {slides[currentSlide].title}
                        </h1>
                        <p style={{ fontSize: 18, lineHeight: 1.8, maxWidth: 700, textAlign: 'center' }}>
                            {slides[currentSlide].content}
                        </p>
                    </>
                )}
            </Modal>
        </div>
    );
};

export default StoryBuilder;
